/* oxlint-disable */
// Generated by scripts/generate-vue-types.mjs. Do not edit.

import type { ComponentPublicInstance as __VueTemplateContext } from 'vue'

import { defineComponent as _defineComponent } from 'vue'
import { createElementVNode as _createElementVNode, unref as _unref, toDisplayString as _toDisplayString, normalizeClass as _normalizeClass, openBlock as _openBlock, createElementBlock as _createElementBlock, createCommentVNode as _createCommentVNode, createTextVNode as _createTextVNode } from "vue"

const _hoisted_1 = { class: "shell" }
const _hoisted_2 = ["aria-busy"]
const _hoisted_3 = {
  class: "service-state",
  role: "status",
  "aria-live": "polite",
  "aria-atomic": "true"
}
const _hoisted_4 = { class: "state-heading" }
const _hoisted_5 = { id: "service-heading" }
const _hoisted_6 = { class: "state-description" }
const _hoisted_7 = { class: "action-dock" }
const _hoisted_8 = ["aria-disabled"]
const _hoisted_9 = {
  key: 1,
  class: "continuity-note"
}

import { computed, onMounted } from 'vue'

import { type Availability, useHealthStore } from './stores/health'


const __sfc__ = /*@__PURE__*/_defineComponent({
  __name: 'App',
  setup(__props) {

const health = useHealthStore()

const statusPresentation = {
  checking: {
    description: 'Confirmando acesso ao serviço autoritativo.',
    label: 'Verificando servidor',
  },
  ready: {
    description: 'O serviço autoritativo está pronto para receber o grupo.',
    label: 'Servidor pronto',
  },
  unavailable: {
    description: 'Não foi possível confirmar o serviço autoritativo. Tente novamente.',
    label: 'Servidor indisponível',
  },
} satisfies Record<Availability, { description: string; label: string }>

const currentStatus = computed(() => statusPresentation[health.availability])

function retry(): void {
  if (health.availability !== 'checking') {
    void health.check()
  }
}

onMounted(() => health.check())

void ((health.availability === 'checking') satisfies boolean | 'true' | 'false')
void ((health.availability === 'checking') satisfies boolean | 'true' | 'false')

return (_ctx: __VueTemplateContext,_cache: any) => {
  return (_openBlock(), _createElementBlock("main", _hoisted_1, [
    _cache[4] || (_cache[4] = _createElementVNode("header", { class: "masthead" }, [
      _createElementVNode("span", {
        class: "cue-mark",
        "aria-hidden": "true"
      }),
      _createElementVNode("h1", null, "Batalha de Hogwarts"),
      _createElementVNode("span", { class: "edition" }, "Mesa cooperativa")
    ], -1 /* CACHED */)),
    _createElementVNode("section", {
      class: _normalizeClass(["service-check", `service-check--${_unref(health).availability}`]),
      "aria-labelledby": "service-heading",
      "aria-busy": _unref(health).availability === 'checking'
    }, [
      _cache[2] || (_cache[2] = _createElementVNode("div", {
        class: "cue-rail",
        "aria-hidden": "true"
      }, [
        _createElementVNode("span", { class: "cue-number" }, "1"),
        _createElementVNode("span", { class: "cue-line" }),
        _createElementVNode("span", { class: "cue-label" }, "Estado oficial")
      ], -1 /* CACHED */)),
      _createElementVNode("div", _hoisted_3, [
        _createElementVNode("div", _hoisted_4, [
          _cache[1] || (_cache[1] = _createElementVNode("span", {
            class: "state-signal",
            "aria-hidden": "true"
          }, null, -1 /* CACHED */)),
          _createElementVNode("h2", _hoisted_5, _toDisplayString(currentStatus.value.label), 1 /* TEXT */)
        ]),
        _createElementVNode("p", _hoisted_6, _toDisplayString(currentStatus.value.description), 1 /* TEXT */)
      ])
    ], 10 /* CLASS, PROPS */, _hoisted_2),
    _createElementVNode("footer", _hoisted_7, [
      (_unref(health).availability !== 'ready')
        ? (_openBlock(), _createElementBlock("button", {
            key: 0,
            class: "retry-button",
            type: "button",
            "aria-disabled": _unref(health).availability === 'checking',
            onClick: _cache[0] || (_cache[0] = ($event: any) => (retry()))
          }, _toDisplayString(_unref(health).availability === 'checking' ? 'Verificando servidor' : 'Tentar novamente'), 9 /* TEXT, PROPS */, _hoisted_8))
        : (_openBlock(), _createElementBlock("p", _hoisted_9, [...(_cache[3] || (_cache[3] = [
            _createElementVNode("span", { "aria-hidden": "true" }, null, -1 /* CACHED */),
            _createTextVNode(" Aguardando a próxima etapa da mesa ", -1 /* CACHED */)
          ]))]))
    ])
  ]))
}
}

})

export default __sfc__
