/* oxlint-disable */
// Generated by scripts/generate-vue-types.mjs. Do not edit.

import type { ComponentPublicInstance as __VueTemplateContext } from 'vue'

import { defineComponent as _defineComponent } from 'vue'
import { createElementVNode as _createElementVNode, unref as _unref, toDisplayString as _toDisplayString, normalizeClass as _normalizeClass, openBlock as _openBlock, createElementBlock as _createElementBlock, createCommentVNode as _createCommentVNode, createTextVNode as _createTextVNode, vModelText as _vModelText, withDirectives as _withDirectives, vModelDynamic as _vModelDynamic, withModifiers as _withModifiers } from "vue"

const _hoisted_1 = { class: "shell" }
const _hoisted_2 = ["aria-busy"]
const _hoisted_3 = {
  class: "service-state",
  role: "status",
  "aria-live": "polite",
  "aria-atomic": "true"
}
const _hoisted_4 = { class: "state-heading" }
const _hoisted_5 = { id: "service-heading" }
const _hoisted_6 = { class: "state-description" }
const _hoisted_7 = {
  key: 1,
  class: "room-success",
  "aria-labelledby": "room-success-heading",
  "aria-live": "polite"
}
const _hoisted_8 = { class: "room-stage room-stage--success" }
const _hoisted_9 = { class: "room-code-block" }
const _hoisted_10 = { "aria-labelledby": "room-code-label" }
const _hoisted_11 = { class: "room-details" }
const _hoisted_12 = {
  key: 0,
  class: "copy-feedback",
  role: "status"
}
const _hoisted_13 = {
  key: 1,
  class: "copy-feedback copy-feedback--error",
  role: "alert"
}
const _hoisted_14 = {
  key: 2,
  class: "room-setup",
  "aria-labelledby": "room-setup-heading"
}
const _hoisted_15 = { class: "room-stage" }
const _hoisted_16 = ["aria-busy"]
const _hoisted_17 = { class: "field" }
const _hoisted_18 = ["aria-invalid", "readonly"]
const _hoisted_19 = {
  id: "display-name-error",
  class: "field-error",
  role: "alert"
}
const _hoisted_20 = { class: "field" }
const _hoisted_21 = { class: "password-control" }
const _hoisted_22 = ["aria-invalid", "type", "readonly"]
const _hoisted_23 = {
  id: "password-error",
  class: "field-error",
  role: "alert"
}
const _hoisted_24 = {
  key: 0,
  class: "form-error",
  role: "alert"
}
const _hoisted_25 = { class: "action-dock" }
const _hoisted_26 = ["aria-disabled"]
const _hoisted_27 = ["disabled"]

import { computed, nextTick, onMounted, ref, watch } from 'vue'

import { type Availability, useHealthStore } from './stores/health'
import { useRoomCreationStore } from './stores/roomCreation'


const __sfc__ = /*@__PURE__*/_defineComponent({
  __name: 'App',
  setup(__props) {

const health = useHealthStore()
const roomCreation = useRoomCreationStore()
const displayName = ref('')
const recoveryPassword = ref('')
const passwordVisible = ref(false)
const copyResult = ref<'idle' | 'copied' | 'failed'>('idle')

const statusPresentation = {
  checking: {
    description: 'Confirmando acesso ao serviço autoritativo.',
    label: 'Verificando servidor',
  },
  ready: {
    description: 'O serviço autoritativo está pronto para receber o grupo.',
    label: 'Servidor pronto',
  },
  unavailable: {
    description: 'Não foi possível confirmar o serviço autoritativo. Tente novamente.',
    label: 'Servidor indisponível',
  },
} satisfies Record<Availability, { description: string; label: string }>

const currentStatus = computed(() => statusPresentation[health.availability])
const displayNameError = computed(() =>
  roomCreation.errorCode === 'INVALID_DISPLAY_NAME'
    ? 'Informe um nome entre 1 e 40 caracteres.'
    : null,
)
const passwordError = computed(() =>
  roomCreation.errorCode === 'WEAK_RECOVERY_PASSWORD'
    ? 'Escolha uma senha mais longa e menos previsível.'
    : null,
)
const formError = computed(() => {
  switch (roomCreation.errorCode) {
    case 'NETWORK_UNAVAILABLE':
      return 'A confirmação não chegou. Tente novamente para consultar a mesma criação.'
    case 'INVALID_DISPLAY_NAME':
    case 'WEAK_RECOVERY_PASSWORD':
    case null:
      return null
    default:
      return 'Não foi possível criar a sala. Revise os dados e tente novamente.'
  }
})

function retry(): void {
  if (health.availability !== 'checking') {
    void health.check()
  }
}

async function createRoom(): Promise<void> {
  await roomCreation.createRoom({
    display_name: displayName.value,
    recovery_password: recoveryPassword.value,
  })

  await nextTick()
  if (roomCreation.roomCreation) {
    document.getElementById('room-success-heading')?.focus()
  } else if (roomCreation.errorCode === 'INVALID_DISPLAY_NAME') {
    document.getElementById('display-name')?.focus()
  } else if (roomCreation.errorCode === 'WEAK_RECOVERY_PASSWORD') {
    document.getElementById('recovery-password')?.focus()
  }
}

function togglePassword(): void {
  passwordVisible.value = !passwordVisible.value
}

async function copyRoomCode(): Promise<void> {
  const code = roomCreation.roomCreation?.room.code
  if (!code) {
    return
  }

  try {
    await navigator.clipboard.writeText(code)
    copyResult.value = 'copied'
  } catch {
    copyResult.value = 'failed'
  }
}

watch([displayName, recoveryPassword], () => roomCreation.resetPendingRequest())

onMounted(() => health.check())

void ((health.availability === 'checking') satisfies boolean | 'true' | 'false')
void ((roomCreation.status === 'submitting') satisfies boolean | 'true' | 'false')
void ((Boolean(displayNameError)) satisfies boolean | 'true' | 'false')
void ((Boolean(passwordError)) satisfies boolean | 'true' | 'false')
void ((health.availability === 'checking') satisfies boolean | 'true' | 'false')
void ((roomCreation.status === 'submitting') satisfies boolean | 'true' | 'false')

return (_ctx: __VueTemplateContext,_cache: any) => {
  return (_openBlock(), _createElementBlock("main", _hoisted_1, [
    _cache[22] || (_cache[22] = _createElementVNode("header", { class: "masthead" }, [
      _createElementVNode("span", {
        class: "cue-mark",
        "aria-hidden": "true"
      }),
      _createElementVNode("h1", null, "Batalha de Hogwarts"),
      _createElementVNode("span", { class: "edition" }, "Mesa cooperativa")
    ], -1 /* CACHED */)),
    (_unref(health).availability !== 'ready')
      ? (_openBlock(), _createElementBlock("section", {
          key: 0,
          class: _normalizeClass(["service-check", `service-check--${_unref(health).availability}`]),
          "aria-labelledby": "service-heading",
          "aria-busy": _unref(health).availability === 'checking'
        }, [
          _cache[7] || (_cache[7] = _createElementVNode("div", {
            class: "cue-rail",
            "aria-hidden": "true"
          }, [
            _createElementVNode("span", { class: "cue-number" }, "1"),
            _createElementVNode("span", { class: "cue-line" }),
            _createElementVNode("span", { class: "cue-label" }, "Estado oficial")
          ], -1 /* CACHED */)),
          _createElementVNode("div", _hoisted_3, [
            _createElementVNode("div", _hoisted_4, [
              _cache[6] || (_cache[6] = _createElementVNode("span", {
                class: "state-signal",
                "aria-hidden": "true"
              }, null, -1 /* CACHED */)),
              _createElementVNode("h2", _hoisted_5, _toDisplayString(currentStatus.value.label), 1 /* TEXT */)
            ]),
            _createElementVNode("p", _hoisted_6, _toDisplayString(currentStatus.value.description), 1 /* TEXT */)
          ])
        ], 10 /* CLASS, PROPS */, _hoisted_2))
      : (_unref(roomCreation).roomCreation)
        ? (_openBlock(), _createElementBlock("section", _hoisted_7, [
            _cache[14] || (_cache[14] = _createElementVNode("div", {
              class: "cue-rail",
              "aria-hidden": "true"
            }, [
              _createElementVNode("span", { class: "cue-number" }, "3"),
              _createElementVNode("span", { class: "cue-line" }),
              _createElementVNode("span", { class: "cue-label" }, "Sala aberta")
            ], -1 /* CACHED */)),
            _createElementVNode("div", _hoisted_8, [
              _cache[11] || (_cache[11] = _createElementVNode("p", {
                class: "service-confirmation",
                role: "status"
              }, [
                _createElementVNode("span", {
                  class: "state-signal",
                  "aria-hidden": "true"
                }),
                _createTextVNode(" Servidor pronto ")
              ], -1 /* CACHED */)),
              _cache[12] || (_cache[12] = _createElementVNode("h2", {
                id: "room-success-heading",
                tabindex: "-1"
              }, "Sala pronta", -1 /* CACHED */)),
              _cache[13] || (_cache[13] = _createElementVNode("p", { class: "stage-description" }, " Este código localiza a sala para o grupo, mas não recupera nenhuma participação. ", -1 /* CACHED */)),
              _createElementVNode("div", _hoisted_9, [
                _cache[8] || (_cache[8] = _createElementVNode("span", { id: "room-code-label" }, "Código da sala", -1 /* CACHED */)),
                _createElementVNode("output", _hoisted_10, _toDisplayString(_unref(roomCreation).roomCreation?.room.code), 1 /* TEXT */)
              ]),
              _createElementVNode("dl", _hoisted_11, [
                _createElementVNode("div", null, [
                  _cache[9] || (_cache[9] = _createElementVNode("dt", null, "Anfitrião da sala", -1 /* CACHED */)),
                  _createElementVNode("dd", null, _toDisplayString(_unref(roomCreation).roomCreation?.participant.display_name), 1 /* TEXT */)
                ]),
                _cache[10] || (_cache[10] = _createElementVNode("div", null, [
                  _createElementVNode("dt", null, "Sessão"),
                  _createElementVNode("dd", null, "Protegida neste navegador")
                ], -1 /* CACHED */))
              ]),
              (copyResult.value === 'copied')
                ? (_openBlock(), _createElementBlock("p", _hoisted_12, "Código copiado."))
                : (copyResult.value === 'failed')
                  ? (_openBlock(), _createElementBlock("p", _hoisted_13, " Não foi possível copiar. Selecione o código e copie manualmente. "))
                  : _createCommentVNode("v-if", true)
            ])
          ]))
        : (_openBlock(), _createElementBlock("section", _hoisted_14, [
            _cache[21] || (_cache[21] = _createElementVNode("div", {
              class: "cue-rail",
              "aria-hidden": "true"
            }, [
              _createElementVNode("span", { class: "cue-number" }, "2"),
              _createElementVNode("span", { class: "cue-line" }),
              _createElementVNode("span", { class: "cue-label" }, "Abrir a mesa")
            ], -1 /* CACHED */)),
            _createElementVNode("div", _hoisted_15, [
              _cache[18] || (_cache[18] = _createElementVNode("p", {
                class: "service-confirmation",
                role: "status"
              }, [
                _createElementVNode("span", {
                  class: "state-signal",
                  "aria-hidden": "true"
                }),
                _createTextVNode(" Servidor pronto ")
              ], -1 /* CACHED */)),
              _cache[19] || (_cache[19] = _createElementVNode("h2", { id: "room-setup-heading" }, "Abra uma sala para o seu grupo", -1 /* CACHED */)),
              _cache[20] || (_cache[20] = _createElementVNode("p", { class: "stage-description" }, " Você será o anfitrião e continuará reconhecido neste navegador, sem criar uma conta. ", -1 /* CACHED */)),
              _createElementVNode("form", {
                id: "create-room",
                class: "room-form",
                "aria-busy": _unref(roomCreation).status === 'submitting',
                onSubmit: _cache[3] || (_cache[3] = _withModifiers(($event: any) => (createRoom()), ["prevent"]))
              }, [
                _createElementVNode("div", _hoisted_17, [
                  _cache[15] || (_cache[15] = _createElementVNode("label", { for: "display-name" }, "Seu nome", -1 /* CACHED */)),
                  _withDirectives(_createElementVNode("input", {
                    "onUpdate:modelValue": _cache[0] || (_cache[0] = ($event: any) => ((displayName).value = $event)),
                    "aria-invalid": Boolean(displayNameError.value),
                    "aria-describedby": "display-name-error",
                    autocomplete: "nickname",
                    id: "display-name",
                    maxlength: "40",
                    name: "display-name",
                    readonly: _unref(roomCreation).status === 'submitting',
                    required: "",
                    type: "text"
                  }, null, 8 /* PROPS */, _hoisted_18), [
                    [_vModelText, displayName.value]
                  ]),
                  _createElementVNode("p", _hoisted_19, _toDisplayString(displayNameError.value), 1 /* TEXT */)
                ]),
                _createElementVNode("div", _hoisted_20, [
                  _cache[16] || (_cache[16] = _createElementVNode("label", { for: "recovery-password" }, "Senha de recuperação", -1 /* CACHED */)),
                  _createElementVNode("div", _hoisted_21, [
                    _withDirectives(_createElementVNode("input", {
                      "onUpdate:modelValue": _cache[1] || (_cache[1] = ($event: any) => ((recoveryPassword).value = $event)),
                      "aria-invalid": Boolean(passwordError.value),
                      type: passwordVisible.value ? 'text' : 'password',
                      "aria-describedby": "password-guidance password-error",
                      autocomplete: "new-password",
                      id: "recovery-password",
                      maxlength: "128",
                      minlength: "12",
                      name: "recovery-password",
                      readonly: _unref(roomCreation).status === 'submitting',
                      required: ""
                    }, null, 8 /* PROPS */, _hoisted_22), [
                      [_vModelDynamic, recoveryPassword.value]
                    ]),
                    _createElementVNode("button", {
                      class: "password-toggle",
                      type: "button",
                      "aria-controls": "recovery-password",
                      onClick: _cache[2] || (_cache[2] = ($event: any) => (togglePassword()))
                    }, _toDisplayString(passwordVisible.value ? 'Ocultar senha' : 'Mostrar senha'), 1 /* TEXT */)
                  ])
                ]),
                _cache[17] || (_cache[17] = _createElementVNode("p", {
                  id: "password-guidance",
                  class: "field-guidance"
                }, " Use ao menos 12 caracteres e evite frases previsíveis. A senha não será exibida de novo. ", -1 /* CACHED */)),
                _createElementVNode("p", _hoisted_23, _toDisplayString(passwordError.value), 1 /* TEXT */),
                (formError.value)
                  ? (_openBlock(), _createElementBlock("p", _hoisted_24, _toDisplayString(formError.value), 1 /* TEXT */))
                  : _createCommentVNode("v-if", true)
              ], 40 /* PROPS, NEED_HYDRATION */, _hoisted_16)
            ])
          ])),
    _createElementVNode("footer", _hoisted_25, [
      (_unref(health).availability !== 'ready')
        ? (_openBlock(), _createElementBlock("button", {
            key: 0,
            class: "retry-button",
            type: "button",
            "aria-disabled": _unref(health).availability === 'checking',
            onClick: _cache[4] || (_cache[4] = ($event: any) => (retry()))
          }, _toDisplayString(_unref(health).availability === 'checking' ? 'Verificando servidor' : 'Tentar novamente'), 9 /* TEXT, PROPS */, _hoisted_26))
        : (_unref(roomCreation).roomCreation)
          ? (_openBlock(), _createElementBlock("button", {
              key: 1,
              class: "primary-button",
              type: "button",
              onClick: _cache[5] || (_cache[5] = ($event: any) => (copyRoomCode()))
            }, _toDisplayString(copyResult.value === 'copied' ? 'Copiar novamente' : 'Copiar código'), 1 /* TEXT */))
          : (_openBlock(), _createElementBlock("button", {
              key: 2,
              class: "primary-button",
              disabled: _unref(roomCreation).status === 'submitting',
              form: "create-room",
              type: "submit"
            }, _toDisplayString(_unref(roomCreation).status === 'submitting'
            ? 'Criando sala'
            : _unref(roomCreation).status === 'failed'
              ? 'Tentar criar novamente'
              : 'Criar sala privada'), 9 /* TEXT, PROPS */, _hoisted_27))
    ])
  ]))
}
}

})

export default __sfc__
