// Closed diagnostic vocabulary. Add only fixed, non-identifying messages.
pub(super) const ROUTES: &[&str] = &[
    "unmatched",
    "/health/live",
    "/health/ready",
    "/health/startup",
    "/api/telemetry",
    "/api/rooms",
    "/api/rooms/{room_code}",
    "/api/rooms/{room_code}/participants",
    "/api/session",
    "/api/session/recover",
    "/api/session/device-sessions",
    "/api/session/device-sessions/{session_id}/revocation",
    "/api/session/protection",
    "/api/rooms/current/protection",
    "/api/session/recovery-password",
    "/api/session/recovery-credential",
    "/api/rooms/current/participants/{position}/recovery-credential",
    "/api/session/hero",
    "/api/session/readiness",
    "/api/games",
    "/api/games/current/commands",
    "/api/games/current/commands/{command_id}",
    "/api/games/current/events",
    "/api/session/events",
];

pub(super) const MESSAGES: &[&str] = &[
    "process panicked",
    "process terminated after an operational failure",
    "HTTP request completed",
    "HTTP server listening",
    "failed to install Ctrl+C signal handler",
    "failed to install SIGTERM signal handler",
    "game expiration scan failed",
    "ignored malformed session revocation notification",
    "initial realtime presence failed",
    "initial security event synchronization failed",
    "initial session revalidation failed",
    "internal operation failed",
    "lifecycle SLO breached",
    "lifecycle measurement unavailable",
    "lifecycle metrics",
    "purge batch failed; retry scheduled",
    "realtime client closed the connection",
    "realtime client watchdog expired",
    "realtime close failed",
    "realtime close write timed out",
    "realtime heartbeat send failed",
    "realtime heartbeat write timed out",
    "realtime peer disconnected",
    "realtime presence disconnect failed",
    "realtime presence heartbeat failed",
    "realtime presence registration failed",
    "realtime receive failed",
    "realtime session revalidation failed",
    "realtime synchronization failed",
    "security event synchronization failed",
    "session revocation listener failed",
    "shutdown signal received",
    "startup initialization completed",
    "startup initialization failed; retrying",
    "realtime presence synchronization failed",
    "realtime presence after official synchronization failed",
];
pub(super) const OPERATIONS: &[&str] = &[
    "advance recovery generation",
    "append game event",
    "append recovery credential security event",
    "begin start-game transaction",
    "claim device session revocation",
    "claim participant protection",
    "claim recovery credential regeneration",
    "claim recovery password rotation",
    "claim room protection",
    "commit game access gate",
    "commit recovery expiration gate",
    "complete device session revocation",
    "complete participant protection",
    "complete recovery credential regeneration",
    "complete recovery password rotation",
    "complete room protection",
    "consume participant recovery credential",
    "create recovered device session",
    "create recovered guest session",
    "device session revocation",
    "disconnect realtime presence",
    "enforce game expiration",
    "enforce locked game expiration",
    "ensure room creation session grant",
    "ensure room join session grant",
    "expire participant device sessions",
    "identity access PostgreSQL operation",
    "identity access application operation",
    "legacy codec shape",
    "list active device sessions",
    "load device session revocation",
    "load participant protection",
    "load participant recovery candidate",
    "load realtime presence",
    "load realtime presence game",
    "load recovery credential regeneration",
    "load recovery password authority",
    "load recovery password rotation",
    "load room protection",
    "load security event position",
    "load security events",
    "lock game access root",
    "lock participant device sessions",
    "lock participant recovery candidate",
    "lock participant recovery room",
    "lock recovery participant",
    "lock recovery participant by position",
    "lock recovery password authority",
    "lock room access root",
    "match application operation",
    "match persistence operation",
    "participant protection",
    "participant recovery transaction",
    "password work failed",
    "persist command receipt",
    "persist game state after command",
    "persist game state replay anchor",
    "protect participant access",
    "protect room access",
    "prune realtime presence",
    "publish replaced guest session",
    "recovery credential regeneration",
    "recovery password rotation",
    "refresh realtime presence",
    "register realtime presence",
    "replace participant device session",
    "resolve presented guest session",
    "revalidate guest session",
    "revalidate guest session in transaction",
    "revoke device session",
    "room protection",
    "rotate recovery password",
    "supersede recovery credentials",
];

pub(super) const OPERATION_LABELS: &[&str] = &[
    "revocation",
    "expiration",
    "event_delivery",
    "realtime_replay",
    "realtime_snapshot",
    "realtime_live",
    "game_socket",
    "security_socket",
    "browser",
    "telemetry_ingest",
    "api",
    "command",
    "recovery",
    "handshake",
    "health",
    "unmatched",
    "telemetry",
    "runtime",
    "integrity",
    "restore",
    "lifecycle",
    "lifecycle_tombstone",
    "lifecycle_detach",
    "lifecycle_purge",
    "lifecycle_verify",
    "lifecycle_complete",
];

pub(super) const OUTCOMES: &[&str] = &[
    "host_assisted",
    "self_service",
    "abandoned",
    "started",
    "unavailable",
    "success",
    "rejected",
    "error",
    "cancelled",
    "rate_limited",
    "violation",
    "uncertain",
    "database_error",
    "ledger_error",
    "orphans",
    "timeout",
];

pub(super) const METRICS: &[&str] = &[
    "access_end_socket_closures",
    "access_end_time_observations",
    "access_end_to_close_upper_bound_seconds",
    "recovery_completions",
    "commit_time_observations",
    "delivery_events",
    "delivery_round_trip_seconds",
    "commit_to_receipt_upper_bound_seconds",
    "socket_write_seconds",
    "socket_writes",
    "socket_closes",
    "socket_lifetime_seconds",
    "realtime_connections",
    "realtime_sync_seconds",
    "realtime_syncs",
    "realtime_backlog",
    "realtime_snapshot_fallbacks",
    "web_lcp_seconds",
    "web_inp_seconds",
    "web_cls_ratio",
    "recovery_journeys",
    "recovery_human_seconds",
    "reconnect_attempts",
    "replay_seconds",
    "snapshot_seconds",
    "long_task_seconds",
    "touch_feedback_seconds",
    "server_heartbeat",
    "executor_lag_seconds",
    "pool_connections",
    "pool_idle_connections",
    "process_resident_bytes",
    "runtime_measurements",
    "http_requests",
    "http_duration_seconds",
    "p0_secret_detected",
    "p0_state_divergence",
    "p0_ack_before_commit",
    "p0_authorization_after_access_end",
    "p0_restore_resurrection",
    "restore_audit_seconds",
    "restore_audits",
    "lifecycle_pending",
    "lifecycle_completed",
    "lifecycle_failed_attempts",
    "lifecycle_detection_p95_seconds",
    "lifecycle_purge_p95_seconds",
    "lifecycle_purge_max_seconds",
    "lifecycle_oldest_pending_seconds",
    "lifecycle_undetected",
    "lifecycle_overdue",
    "lifecycle_orphan_jobs",
    "lifecycle_stage_pending",
    "lifecycle_batch_seconds",
    "lifecycle_batches",
    "lifecycle_measurements",
    "worker_heartbeat",
    "pool_wait_seconds",
    "lock_seconds",
    "rule_seconds",
    "sql_seconds",
    "commit_seconds",
    "response_prepare_seconds",
    "queue_wait_seconds",
    "password_seconds",
];
