// Generated by scripts/generate-contracts.mjs. Do not edit.

export const healthStatuses = ["alive","started","starting","ready","unavailable"] as const

export type HealthStatus = (typeof healthStatuses)[number]

export interface HealthResponse {
  status: HealthStatus
}
